'use strict';

var path = require( 'path' );
var fs = require( 'fs-extra' );
var url = require( 'url' );
var yargs = require( 'yargs' );
var async = require( 'async' );
var request = require('request');



function getOutPath( outdir, urlstr ) {
	var parsed = url.parse( urlstr );
	return path.join( outdir, parsed.path );
}


function buildNewUrl( newRootUrl, urlstr ) {
	var parsed = url.parse( urlstr );
	if ( newRootUrl[ newRootUrl.length-1 ] !== '/' ) {
		newRootUrl += '/';
	}
	var suffix = parsed.path;
	if ( suffix[0] === '/' ) {
		suffix = suffix.substr( 1 );
	}
	return newRootUrl + suffix;
}


function getFilesToDownload( swjson, newRootUrl, outdir, output ) {
	output = output || [];
	if ( !swjson.dependencies ) {
		return output;
	}
	for ( var name in swjson.dependencies ) {
		if ( swjson.dependencies.hasOwnProperty( name ) ) {
			var dep = swjson.dependencies[ name ];
			if ( dep.resolved ) {
				var outpath = getOutPath( outdir, dep.resolved );
				var newUrl = buildNewUrl( newRootUrl, dep.resolved );
				output.push( { url: dep.resolved, out: outpath } );
				dep.resolved = newUrl;
			}
			getFilesToDownload( dep, newRootUrl, outdir, output );
		}
	}
	return output;
}


function download( file, callback ) {
	var dir = path.dirname( file.out );
	fs.ensureDirSync( dir );
	console.log( "Downloading " + file.url );
	request
		.get( file.url )
		.on( 'error', function( err ) {
			callback( err );
		} )
		.pipe( fs.createWriteStream( file.out ) )
		.on( 'error', function( err ) {
			callback( err );
		} )
		.on( 'close', function() {
			callback();
		} );
}


function start() {
	var options = yargs
		.option( 'shrinkwrap', {
			describe: 'Input shrinkwrap file generated by npm',
			default: 'npm-shrinkwrap.json'
		} )
		.option( 'outdir', {
			describe: 'Output directory to put web server contents',
			default: 'www'
		} )
		.option( 'outshrinkwrap', {
			describe: 'Outputs modified shrinkwrap file to another file (defaults to modifying input file)'
		} )
		.option( 'url', {
			describe: 'URL to write into the new shrinkwrap json that will hold the mirrored npm dependencies',
			demand: true
		} )
		.usage('Usage: $0 [options]')
		.example('$0 --url http://localhost', 'Reads in ./npm-shrinkwrap.json and outputs to www directory')
		.example('$0 --url http://localhost --shrinkwrap /home/user/project/npm-shrinkwrap.json --outdir /var/www', 'Reads specified shrinkwrap json file and outputs to specified www directory')
		.help( 'help' )
		.argv;
		
	options.shrinkwrap = path.resolve( options.shrinkwrap );
	if ( !fs.existsSync( options.shrinkwrap ) ) {
		console.error( "Shrinkwrap file '" + options.shrinkwrap + "' not found!" );
		return;
	}
	if ( !options.outshrinkwrap ) {
		options.outshrinkwrap = options.shrinkwrap;
	}
	options.outshrinkwrap = path.resolve( options.outshrinkwrap );
	
	var swjson = JSON.parse( fs.readFileSync( options.shrinkwrap ) );

	options.outdir = path.resolve( options.outdir );
	fs.ensureDirSync( options.outdir );
	var files = getFilesToDownload( swjson, options.url, options.outdir );
	async.eachLimit( files, 4, download, function( err ) {
		if ( err ) {
			console.error( "Failed to download" );
			console.error( err );
		} else {
			fs.writeFileSync( options.outshrinkwrap, JSON.stringify( swjson, null, 2 ) );	
			console.log( "Complete" );
		}
	} );
}


start();

