'use strict';

var yargs = require( 'yargs' );
var mirror = require( './index.js' );

function start() {
	var options = yargs
		.option( 'shrinkwrap', {
			describe: 'Input shrinkwrap file generated by npm',
			default: 'npm-shrinkwrap.json'
		} )
		.option( 'outdir', {
			describe: 'Output directory to put web server contents',
			default: 'www'
		} )
		.option( 'outshrinkwrap', {
			describe: 'Outputs modified shrinkwrap file to another file (defaults to modifying input file)'
		} )
		.option( 'url', {
			describe: 'URL to write into the new shrinkwrap json that will hold the mirrored npm dependencies',
			demand: true
		} )
		.usage('Usage: npm-mirror [options]')
		.example('npm-mirror --url http://localhost', 'Reads in ./npm-shrinkwrap.json and outputs to www directory')
		.example('npm-mirror --url http://localhost --shrinkwrap /home/user/project/npm-shrinkwrap.json --outdir /var/www', 'Reads specified shrinkwrap json file and outputs to specified www directory')
		.help( 'help' )
		.argv;

	mirror( options );
}


start();

